export const MAKE_AUTH_REQUEST = "MAKE_AUTH_REQUEST";

export const MAKE_AUTH_SUCCESS = "MAKE_AUTH_SUCCESS";

export const MAKE_AUTH_FAILURE = "MAKE_AUTH_FAILURE";

export const MAKE_AUTH_CLEAR = "MAKE_AUTH_CLEAR";

export const AUTHENTICATION_CALLBACK_SUCCESS =
  "AUTHENTICATION_CALLBACK_SUCCESS";

export const SET_PROFILE_DETAILS = "SET_PROFILE_DETAILS";

export const SET_TRENDING_DATA = "SET_TRENDING_DATA";

export const SET_NOTIFICATION = "SET_NOTIFICATION";

export const GET_TWEETS_REQUEST = "GET_TWEETS_REQUEST";

export const GET_TWEETS_REQUEST_SUCCESS = "GET_TWEETS_REQUEST_SUCCESS";

export const GET_TWEETS_REQUEST_FAILED = "GET_TWEETS_REQUEST_FAILED";

export const GET_TWEETS_REQUEST_CLEAR = "GET_TWEETS_REQUEST_CLEAR";

export const LOGOUT_USER = "LOGOUT_USER";



